History
muskanbagrecha/video-library-react-app pull request #6
Opened 2022-04-05 14:14 UTC by muskanbagrecha

Please review PR for history and playlist functionality.
PS: Please ignore console logs for now. I will remove it in my next PR.

Files to view: [files](https://github.com/muskanbagrecha/video-library-react-app/pull/6/files?file-filters%5B%5D=.jsx&show-deleted-files=true&show-viewed-files=true)

UI/UX changes are welcome but I will not be implementing them on priority as of now.

2022-04-05 16:31 UTC, Debarshi95 approved these changes
Some comments added, may be work on  them. 
Liked that you use used seperate context for separate things. 
In few cases the logic can be improved, may be work on them later.

2022-04-05 16:31 UTC, Debarshi95 commented on src/Context/playlistContext.jsx
> +  };
Remove console logs

2022-04-05 16:31 UTC, Debarshi95 commented on src/Context/playlistContext.jsx
> +const token = localStorage.getItem("user")
May be instead of the ternary operator you can directly use JSON.parse(localStorage.getItem("user"))?.token

2022-04-05 16:31 UTC, Debarshi95 commented on src/Pages/HistoryPage/HistoryPage.jsx
> +        </div>
Nested ternary operators are usually not used. May be abstract out the logic and render separate components.

2022-04-05 16:31 UTC, Debarshi95 commented on src/Pages/PlaylistPage/Components/PlaylistCard/PlaylistCard.jsx
> +    navigate("/playlist/" + _id);
Suggestion: use template strings in such cases.

2022-04-05 16:31 UTC, Debarshi95 commented on src/Pages/PlaylistPage/Components/PlaylistModal/PlaylistModal.jsx
> +    console.log("effect playlist");
Remove console log

2022-04-05 16:31 UTC, Debarshi95 commented on src/Pages/PlaylistPage/Components/PlaylistModal/PlaylistModal.jsx
> +    if (playlists === null) {
Instead of checking if playlist is equal to null, you can check 
 if(!playlists)

2022-04-05 16:31 UTC, Debarshi95 commented on src/Pages/VideoPage/Components/VideoListing/VideoCard.jsx
> +      {type === "HISTORY_CARD" && (
Using hardcoded strings in such is not recommended.

2022-04-05 19:47 UTC, zoef-yt requested changes

2022-04-05 19:47 UTC, zoef-yt commented on src/Components/UI/Modal/Modal.css
> +    background-color: rgba(0, 0, 0, 0.8);
Use var to stay consistent.

2022-04-05 19:47 UTC, zoef-yt commented on src/Components/UI/Modal/Modal.jsx
> +  const classes = "modal " + (modalClass ? modalClass : "");
string literal can be used here.

2022-04-05 19:47 UTC, zoef-yt commented on src/Context/historyContext.jsx
> +import { useEffect } from "react";
Import react hooks in 1 line.

2022-04-05 19:47 UTC, zoef-yt commented on src/Context/historyContext.jsx
> +  const token = localStorage.getItem("user")
You can directly use Optional chaining here.

2022-04-05 19:47 UTC, zoef-yt commented on src/CustomHooks/index.jsx
> +import { usePlaylist } from "./usePlaylist";
You can directly export them you don't need an extra export statement.

2022-04-05 19:47 UTC, zoef-yt commented on src/index.css
> +} */
Remove commented code.

2022-04-05 19:47 UTC, zoef-yt commented on src/index.css
> +    max-width: 1580px;
This value can be in rems.

2022-04-05 19:47 UTC, zoef-yt commented on src/Pages/index.jsx
>  import { NotFound } from "./NotFound/NotFound";
Same here you can just export directly.

2022-04-05 19:47 UTC, zoef-yt commented on src/Pages/VideoPage/VideoPage.jsx
>        {/* {videoLoader && <img src={spinner} alt="loading.." />} */}
Remove commented code.

2022-04-05 19:47 UTC, zoef-yt commented on src/Pages/VideoPage/Components/VideoListing/VideoCard.jsx
>  import { useEffect } from "react";
keep react hooks in one import.

2022-04-05 19:47 UTC, zoef-yt commented on src/Pages/SinglePlaylistPage/SinglePlaylistPage.jsx
> +        </>
You don't need fragment here you can directly use h3.

2022-04-05 19:47 UTC, zoef-yt commented on src/Pages/SignupPage/Components/SignupForm.jsx
> +  // const { setShowModal } = usePlaylistModal();
Remove commented code.

2022-04-05 19:47 UTC, zoef-yt commented on src/Pages/PlaylistPage/Components/PlaylistModal/PlaylistModal.css
> +    width: 0.5rem;
Remove commented code.

2022-04-05 19:47 UTC, zoef-yt commented on src/Pages/PlaylistPage/Components/PlaylistCard/PlaylistCard.css
> +    /* flex-direction: column; */
Remove commented code.

2022-04-05 19:47 UTC, zoef-yt commented on src/Pages/LoginPage/Components/LoginForm.jsx
> +          // setShowModal(false);
Remove commented code.

2022-04-05 19:47 UTC, zoef-yt commented on src/Pages/LoginPage/Components/LoginForm.jsx
> +  // const { setShowModal } = usePlaylistModal();
Remove commented code.

2022-04-05 19:47 UTC, zoef-yt commented on src/Pages/Homepage/Components/Category/CategorySection.css
>      border: 1px solid #cccccc;
Use var to stay consistent.

2022-04-05 19:47 UTC, zoef-yt commented on src/Pages/ExplorePage/ExploreFilter.jsx
>                : "")
Use string literal here.

2022-04-06 04:31 UTC, zoef-yt approved these changes
Really great work with the UI. I absolutely love the approach in your code. Nice work with the whole functionality of the playlist looks cool. Great job Muskan. You are good to merge.

2022-04-06 05:19 UTC, merged